apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-cluster-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: matthew@matthewdavis.io
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
